### ISSUE TITLE
Add build procress

### ISSUE THREAD

**Issue by marcobiedermann** [rohitkrai03/pills#10]
There are no instructions which tools are used to compile and to minify the scss files.
I suggest adding a task runner like [gulp](http://gulpjs.com/) or [Grunt](http://gruntjs.com/)

**Comment by marcobiedermann** [comment]
I also suggest adding some continuous integration like [Travis CI](https://travis-ci.org/).
This will check each commit for some potential errors.

**Comment by jarrydfillmore** [comment]
+1, this would help me a lot!

**Comment by rohitkrai03** [comment]
The gulp build has already been added and will add travis-ci later on.
