### ISSUE TITLE
Prefix classes

### ISSUE THREAD

**Issue by marcobiedermann** [rohitkrai03/pills#13]
In my opinion `row` and `column` are too generic.
I suggest prefixing it with either `grid-`, `pills-` or `p-`.

**Comment by NetOpWibby** [comment]
I think the simplicity is perfect. Prefixes only serve to make the library become bloated like virtually every other grid system.

**Comment by jdfweb** [comment]
Agreed @NetOperatorWibby !

**Comment by rohitkrai03** [comment]
I agree with not adding unnecessary prefix classes and make class name complex. Closing the issue.
