### ISSUE TITLE
Different layouts on different screen sizes?

### ISSUE THREAD

**Issue by ghost** [rohitkrai03/pills#9]
Nice library.

Apologies if I missed something - but how would I go about having a set of elements occupy a different number of cols on different screen sizes? 

Say I had a set of divs that were to be 4 cols on a large screen, 6 cols on a med screen, and 12 cols on a small screen... 

I can see in the demo that everything changes to a single column when the window is mobile portrait sized. Is this the only "responsiveness" available?

Thank you

**Comment by rohitkrai03** [comment]
This framework was built keeping in mind the simplicity of fluid and responsive layouts. That is why there is no option for defining different cols for different screen sizes.
